version: "3.8"
services:
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - service_1
      - service_2

  service_1:
    build: ./service_1
    ports:
      - "8001:8001"

  service_2:
    build: ./service_2
    ports:
      - "8002:8002"
