version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2
    restart: unless-stopped

  service_1:
    build: ./service_1
    container_name: service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped

  service_2:
    build: ./service_2
    container_name: service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
